version: '3.8'
services:
  music-disc:
    image: hmes98318/music-disc:2.0.2
    container_name: music-disc
    restart: always
    environment:
      TOKEN: "your_token"
      PREFIX: "+"
      PLAYING: "+help | music"
      EMBEDS_COLOR: "#FFFFFF"
      DEFAULT_VOLUME: 50
      MAX_VOLUME: 100
      AUTO_LEAVE: "true"
      AUTO_LEAVE_COOLDOWN: 5000
      DISPLAY_VOICE_STATE: "true"
      TZ: "Asia/Kolkata"
    volumes:
      - ./node-list.json:/bot/node-list.json
      - ./blacklist.json:/bot/blacklist.json
    # ports:
    #   - 33333:33333

  lavalink:
    image: fredboat/lavalink:3.7.8 # pin the image version to Lavalink v3
    container_name: lavalink_v3
    restart: unless-stopped
    environment:
      _JAVA_OPTIONS: -Xmx125M # set Java options here
      SERVER_PORT: 2333 # set lavalink server port
      LAVALINK_SERVER_PASSWORD: youshallnotpass # set password for lavalink
      TZ: "Asia/Kolkata"
    volumes:
      - ./server/application.yml:/opt/Lavalink/application.yml # mount application.yml from the same directory or use environment variables
      - ./server/plugins/:/opt/Lavalink/plugins/ # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
    expose:
      - 2333 # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
    # ports:
    #     - 2333:2333 # you only need this if you want to make your lavalink accessible from outside of containers
