version: "3"
services:
  music-disc:
    image: hmes98318/music-disc:2.1.3
    container_name: music-disc
    restart: always
    environment:
      BOT_TOKEN: "your_token"
      BOT_PREFIX: "+"
      BOT_PLAYING: "+help | music"
      BOT_EMBEDS_COLOR: "#FFFFFF"
      DEFAULT_VOLUME: 50
      MAX_VOLUME: 100
      AUTO_LEAVE: "true"
      AUTO_LEAVE_COOLDOWN: 5000
      DISPLAY_VOICE_STATE: "true"
      TZ: "Asia/Kolkata"
      ENABLE_LOCAL_NODE: true
      LOCAL_NODE_AUTO_RESTART: true
    volumes:
      - ./node-list.json:/bot/node-list.json
      - ./blacklist.json:/bot/blacklist.json
    depends_on:
      lavalink:
        condition: service_healthy
    # ports:
    #   - 33333:33333

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3.7.11 # pin the image version to Lavalink v3
    container_name: lavalink_v3
    restart: unless-stopped
    environment:
      _JAVA_OPTIONS: -Xmx125M # set Java options here
      SERVER_PORT: 2333 # set lavalink server port
      LAVALINK_SERVER_PASSWORD: youshallnotpass # set password for lavalink
      TZ: "Asia/Kolkata"
    volumes:
      - ./server/application.yml:/opt/Lavalink/application.yml # mount application.yml from the same directory or use environment variables
      - ./server/plugins/:/opt/Lavalink/plugins/ # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
    expose:
      - 2333 # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
    # ports:
    #     - 2333:2333 # you only need this if you want to make your lavalink accessible from outside of containers
    healthcheck:
      test: curl http://localhost:2333 || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
